// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwSMyk8WjpNiTFd651J9SYrVy_KefFRsA',
    appId: '1:934780383532:web:d6e1fc8ef75bc67ed9bc89',
    messagingSenderId: '934780383532',
    projectId: 'simrs-mobile-app',
    authDomain: 'simrs-mobile-app.firebaseapp.com',
    storageBucket: 'simrs-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1oWxX8CHKxVIyLJl66gcYT98EHffXpmc',
    appId: '1:934780383532:android:3c13ce1f40d04be8d9bc89',
    messagingSenderId: '934780383532',
    projectId: 'simrs-mobile-app',
    storageBucket: 'simrs-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTSnH3EcklFO47x72CaV2FUv0P3Iv0Irs',
    appId: '1:934780383532:ios:44a7ba0920a16d85d9bc89',
    messagingSenderId: '934780383532',
    projectId: 'simrs-mobile-app',
    storageBucket: 'simrs-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.simrsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTSnH3EcklFO47x72CaV2FUv0P3Iv0Irs',
    appId: '1:934780383532:ios:44a7ba0920a16d85d9bc89',
    messagingSenderId: '934780383532',
    projectId: 'simrs-mobile-app',
    storageBucket: 'simrs-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.simrsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwSMyk8WjpNiTFd651J9SYrVy_KefFRsA',
    appId: '1:934780383532:web:5bd5a35340eddb9ed9bc89',
    messagingSenderId: '934780383532',
    projectId: 'simrs-mobile-app',
    authDomain: 'simrs-mobile-app.firebaseapp.com',
    storageBucket: 'simrs-mobile-app.firebasestorage.app',
  );

}